package io.snyk.eclipse.plugin;

public interface EnvironmentConstants {
  String ENV_SNYK_API = "SNYK_API";
  String ENV_SNYK_TOKEN = "SNYK_TOKEN";
  String ENV_SNYK_ORG = "SNYK_CFG_ORG";
  String ENV_DISABLE_ANALYTICS = "SNYK_CFG_DISABLE_ANALYTICS";
  String ENV_INTERNAL_SNYK_OAUTH_ENABLED = "INTERNAL_SNYK_OAUTH_ENABLED";
  String ENV_INTERNAL_OAUTH_TOKEN_STORAGE = "INTERNAL_OAUTH_TOKEN_STORAGE";
  String ENV_OAUTH_ACCESS_TOKEN = "SNYK_OAUTH_TOKEN";
}
