# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/tutorials/build-and-test-code/java-with-maven

name: Build Plugin with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - uses: pmd/pmd-github-action@v2
        name: Lint
        id: pmd
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
            rulesets: 'plugin/src/main/resources/pmd-ruleset.xml'
            sourcePath: 'plugin/src/main/java'
            analyzeModifiedFilesOnly: true

      - name: Upload SARIF file
        if: ${{ matrix.os == 'ubuntu-latest' && steps.pmd.outputs.violations != 0 }}
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: pmd-report.sarif

      - name: Fail build if violations found
        if: steps.pmd.outputs.violations != 0
        run: exit 1

      - name: Build with Maven
        run: ./mvnw clean verify -DtrimStackTrace=false
